name: Angular Frontend CI/CD

on:
  push:
    branches: [ "main" ]
    paths: [ "blog-ui/**" ] # Triggers ONLY when files inside the frontend folder change

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./blog-ui # Tells GitHub to run all commands inside the frontend folder
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './blog-ui/package-lock.json' # Fixes cache path for monorepos

      - name: Install Dependencies
        run: npm ci

      # - name: Run Frontend Tests
      #   run: npm run test -- --watch=false --browsers=ChromeHeadless
      #   continue-on-error: true # Prevents pipeline from stopping if you haven't written tests yet

      - name: Build Production Bundle
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1" # Replace with your exact AWS S3 region

      - name: Sync Production Build Assets to Amazon S3 Bucket
        run: |
          # Sync command points directly to the compilation subfolder inside frontend
          aws s3 sync dist/blogweb/browser/ s3://github-test-blog --delete
